# Generated by Django 5.2.14 on 2026-05-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='vehicle_model',
        ),
    ]
