# Generated by Django 5.2.14 on 2026-05-15 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0002_rename_model_vehicle_vehicle_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aguardando aprovacao', 'Aguardando Aprovação'), ('aguardando pecas', 'Aguardando Peças'), ('em andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('entregue', 'Entregue')], default='aberta', max_length=50)),
                ('description_problem', models.TextField()),
                ('description_service', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_orders', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
